environment:

  matrix:
    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python27-x64"

init:
  - ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%



install:
  - set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%
  - set PYTHONPATH=%PYTHONPATH%;%cd%\src;%PYTHON%\\Lib;%PYTHON\\DLLs
  - "python -m pip install cryptography"
  - "python setup.py build"
  - "python setup.py install"


build: off

# test_script:

# after_test:

# artifacts:
#   - path: dist\*

#on_success:
